name: Continuous Integration

on: push

jobs:
  test-msbuild-on-windows:

    runs-on: windows-latest
    steps:
      - name: Test variables
        run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY | xxd
        shell: bash
