name: Continuous Integration

on: push

jobs:
  test-curl-on-ubuntu:

    runs-on: ubuntu-latest
    steps:
      - name: Test if curl is available
        run: curl

  test-curl-on-windows:

    runs-on: windows-latest
    steps:
      - name: Test if curl is available
        run: curl
