name: Continuous Integration

on: push

jobs:
  test-msbuild-on-windows:

    runs-on: windows-latest
    steps:
      - name: Test variables
        shell: bash
        run: |

          uriencode() {
            s="${1//'%'/%25}"
            s="${s//' '/%20}"
            s="${s//'"'/%22}"
            s="${s//'#'/%23}"
            s="${s//'$'/%24}"
            s="${s//'&'/%26}"
            s="${s//'+'/%2B}"
            s="${s//','/%2C}"
            s="${s//'/'/%2F}"
            s="${s//':'/%3A}"
            s="${s//';'/%3B}"
            s="${s//'='/%3D}"
            s="${s//'?'/%3F}"
            s="${s//'@'/%40}"
            s="${s//'['/%5B}"
            s="${s//']'/%5D}"
            printf %s "$s"
          }

          REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/
          ISSUE_URL=$REPO_URL/issues/
          README_URL=https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/README.md

          PUBLISH_URL="https://www.vsixgallery.com/api/upload\
          ?repo=$(uriencode $REPO_URL)\
          &issuetracker=$(uriencode $ISSUE_URL)\
          &readmeUrl=$(uriencode $README_URL)"

          echo curl \
            -i \
            -X POST \
            --form file=@src/Vinyl.Vsix/bin/Release/net472/Vinyl.Vsix.vsix \
            $PUBLISH_URL | xxd