name: Continuous Integration

on: push

jobs:
  test-msbuild-on-windows:

    runs-on: windows-latest
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Test if msbuild is available
        run: msbuild
