name: Continuous Integration

on: push

jobs:
  test-msbuild-on-windows:

    runs-on: windows-latest
    steps:
      - name: Test variables
        run: "echo The URL is: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
        shell: bash
